Aaronreadmeupdate2
banked/example-store pull request #13
Opened 2021-09-09 12:46 UTC by Aarontball

2021-09-09 12:52 UTC, jusoskina requested changes

2021-09-09 12:52 UTC, jusoskina commented on README.md
> +This dummy ecommerce store uses shoes as a product, it's purpose is to demonstrate an implementation of Banked's hosted checkout, used for account to account payments. You can add products to a baske
Hey @Aarontball can you get rid of the extra full stops before merging :)

2021-09-09 12:58 UTC, Aarontball commented on README.md
> +This dummy ecommerce store uses shoes as a product, it's purpose is to demonstrate an implementation of Banked's hosted checkout, used for account to account payments. You can add products to a baske
@jusoskina I will try :)

2021-09-09 13:23 UTC, jusoskina approved these changes

2021-09-10 09:31 UTC, jusoskina commented
approved the PR, but not merging. Closing the PR and deleting branch

2021-09-10 09:31 UTC, closed without merging